name: Build MyVLESS
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: JDK 17
        uses: actions/setup-java@v4
        with: { java-version: 17, distribution: temurin }
      - name: Android SDK
        run: |
          mkdir -p ~/.android && touch ~/.android/repositories.cfg
          curl -L https://github.com/termux/proot/raw/master/proot -o /tmp/proot && chmod +x /tmp/proot
          yes | sdkmanager platforms\;android-34 build-tools\;34.0.0
      - name: shim
        run: |
          mkdir -p res app/src/main/res/mipmap-anydpi-v26 app/src/main/res/values app/pro-guard app/src/main/res/avatar
          echo ' '> app/pro-guard
          echo "test" > app/src/main/res/values/strings.xml
      - name: build
        run: gradle assembleRelease
      - name: upload
        uses: actions/upload-artifact@v4
        with: { name: MyVLESS-APK, path: app/build/outputs/apk/release/app-release-unsigned.apk }
